### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [NoahFinberg/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out.

Hint: It's best to include a link to the specific commit where you added the mobile meta tag directly in the comments :)

**Comment by NoahFinberg** [comment]
https://github.com/NoahFinberg/splurty/commit/76f09f77232b46c59ca912b9b9c38cc0c18234ce

Let me know if this resolved the issue.

**Comment by MarcoMorawec** [comment]
Thumbs up!

Make sure you close the issue now that you resolved it :)

On Tuesday, May 19, 2015, NoahFinberg notifications@github.com wrote:

> 76f09f7
> https://github.com/NoahFinberg/splurty/commit/76f09f77232b46c59ca912b9b9c38cc0c18234ce
> 
> Let me know if this resolved the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NoahFinberg/splurty/issues/1#issuecomment-103516377.

## 

_Marco Morawec_
theFirehoseProject http://www.thefirehoseproject.com/
(808) 347-1135
